{
 "title": "Throughput",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Facts Saved",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(facts_saved_total{}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offerings Created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(university_offering_created_total{}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Facts Loaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(facts_loaded_total{}[$__rate_interval]) )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicator Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"back-end-replicator\"} | json | severity = `WARN` | line_format `{{.body}}`"
    }
   ]
  }
 ]
}