server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: dockerlogs
          __path__: /var/log/containers/*
    pipeline_stages:
      - json:
          expressions:
            timestamp: time
            level: level
            msg: msg
            logger: logger
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          logger:
