name: university-mesh

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.15
    platform: "linux/amd64"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

  back-end-replicator:
    image: jinaga/jinaga-replicator:latest
    container_name: back-end-replicator
    ports:
      - "8080:8080"
    volumes:
      - ./policies:/var/lib/replicator/policies:ro
      - ./authentication:/var/lib/replicator/authentication:ro
      - ./subscriptions:/var/lib/replicator/subscriptions:ro

  importer:
    build:
      context: ../src
      dockerfile: University.Importer/Dockerfile
    environment:
      - REPLICATOR_URL=http://back-end-replicator:8080
      - ENVIRONMENT_PUBLIC_KEY=default-public-key
    depends_on:
      - back-end-replicator

volumes:
  esdata:
